---
language: python
python: 3.8.2

services:
  - docker

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible molecule docker
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - molecule test
