---
- name: Converge
  hosts: all
  vars:
    openproject_dir: '/opt/openproject'
  become: true
  tasks:

    - name: Create the openproject dirs
      file:
        state: directory
        path: '{{ openproject_dir }}/{{ item }}'
        #mode: 0755
      loop:
        - assets
        - pgdata

    - name: Create docker network
      docker_network:
        name: openproject

    - name: Include ansible-role-openproject
      include_role:
        name: ansible-role-openproject
      vars:
        openproject_db_password: passwo4d
        openproject_secret_key_base: secret
        openproject_docker_ports: ['127.0.0.1:8080:8080']
        openproject_docker_network:
          - name: openproject

    - name: Wait for openproject to boot
      uri:
        url: http://localhost:8080/api/v3
        status_code: 200
      register: result
      until: result.status == 200
      retries: 300
      delay: 1
