---
- name: Converge
  hosts: localhost
  tasks:
    - debug:
        msg: 'Temp dir in {{ openproject_dir }}'

    - name: Include ansible-role-openproject
      include_role:
        name: ansible-role-openproject
      vars:
        openproject_secret_key_base: secret
        openproject_docker_ports: ['80:80']
        openproject_config: |
          default:
            disable_password_choice: true


    - name: Wait for openproject to boot
      uri:
        url: http://localhost/api/v3
        status_code: 200
      register: result
      until: result.status == 200
      retries: 300
      delay: 1
