---
lint: |
  set -e
  yamllint -d relaxed .
  ansible-lint
  flake8
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  #- name: ubuntu
    #image: geerlingguy/docker-ubuntu2004-ansible
    #volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup:ro
    #command: /lib/systemd/systemd
    #privileged: true
    #pre_build_image: true
  - name: instance
    image: docker:stable-dind
    command: /usr/local/bin/dockerd-entrypoint.sh
    privileged: true
    tty: true
    interactive: true
    detach: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu:
        ansible_user: ansible
verifier:
  name: ansible
