---
lint: |
  set -e
  yamllint -d relaxed .
  ansible-lint -x 208
  flake8
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker:stable-dind
    command: /usr/local/bin/dockerd-entrypoint.sh
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
        #    privileged: true
        #    tty: true
        #    interactive: true
        #    detach: true
provisioner:
  name: ansible
verifier:
  name: ansible
