---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: install python3
      apk:
        name: python3-dev,py3-pip,py3-cryptography
        update_cache: yes
    - name: install docker package from pip
      pip:
        name: docker
    #- name: updating apt-cache
      #apt:
        #update_cache: true
        #cache_valid_time: 86400
        #force_apt_get: true
        ##    - name: install docker dependencies
        ##      apt:

