---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: install python3
      apk:
        name: python3-dev,py3-pip,py3-cryptography
        update_cache: yes
    - name: install docker package from pip
      pip:
        name: docker
