---
- name: Verify
  hosts: localhost
  tasks:
  - name: Read the openproject config
    slurp:
      src: '{{ openproject_dir }}/config/configuration.yml'
    register: config_contents_b64

  - set_fact:
      config_contents: '{{ config_contents_b64.content | b64decode | from_yaml }}'

  - debug: var=config_contents

  - name: Example assertion
    assert:
      that: 'config_contents.default.disable_password_choice is true'
