---
name: Molecule tests

on:
  push:
    #branches: [ $default-branch ]
    branches: ['*']
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Poetry
      run: |
        sudo apt install python3-setuptools python3-wheel
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    #- name: Install dependencies
      #run: |
        #pip3 install poetry==1.0.5
        #poetry config virtualenvs.create false
        #poetry install --no-interaction --no-ansi
    - name: Run molecule
      run: |
        . $HOME/.poetry/env && poetry run molecule test --all
