---
name: Molecule tests

on:
  push:
    #branches: [ $default-branch ]
    branches: ['*']
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: Gr1N/setup-poetry@v4
    - run: poetry --version

    - name: Install Poetry
      run: |
        poetry --version
        ls -la
        ls -la ../
        poetry install --no-interaction --no-ansi
    - name: Run molecule
      run: |
        poetry run molecule test --all
